### ISSUE TITLE
refresh_token was replaced by xsrfToken

### ISSUE THREAD

**Issue by g-mocken** [edent/Renault-Zoe-API#16]
Just recently, in the login answer, the refresh_token was replaced by a xsrfToken.
As a result, refreshing no longer works. The login token's typical validity was also reduced from many hours to a few minutes.

**Comment by jamesremuscat** [comment]
Thanks for the research - there's a bit more to it (at least there is now - one gets the impression that they're tinkering with production code somewhat...)

Now when you hit `/login`, the response includes a `Set-Cookie` header containing a `refreshToken` cookie. When you `POST` to `/refresh` you'll need to include that refresh token in a `Cookie` header, as well as the `X-XSRF-TOKEN` header containing the `xsrfToken` from the login response body.

I'm sure all this seemed a good idea to someone at the time.

**Comment by g-mocken** [comment]
Well, for me and the iOS/swift code that I am currently working on, the renewal is still working without explicit such Cookie-Headers. Not sure why, because when I use curl in command line, I do indeed get a "Missing cookie 'refreshToken' " error...

**Comment by epenet** [comment]
I've posted a PullRequest relating to this #17

**Comment by ruditb** [comment]
Yesterday when I refreshed the token I figured out, that the refreshToken from the cookie only works with the token you received with the cookie. If you try to refresh the token you have received from the previous refresh you fail. The reason is, that when you receive a refreshed token they also send a new refreshToken via cookie. As the token has a vlidation time of 15 minutes the refreshToken has a validation time of 24 Hours.
So at the very end if you refresh a token you get a new token and a new refreshToken via cookie which you have to use then. The xrsfToken can be reused.

**Comment by edent** [comment]
I can't accept #17 because I no longer have the vehicle to test with.

If a couple of you test it and report back that it works, I'll merge it.

**Comment by tobintax** [comment]
Tried it: 

Traceback (most recent call last):
  File "zoe-console.py", line 32, in <module>
    zeServices = ZEServices(credentials['ZEServicesUsername'], credentials['ZEServicesPassword'])
  File "/mnt/fronius-pv/scripts/Renault-Zoe-API-master/python/shared/zeservices.py", line 25, in __init__
    self.accessToken = self.getAccessToken(user, password)
  File "/mnt/fronius-pv/scripts/Renault-Zoe-API-master/python/shared/zeservices.py", line 31, in getAccessToken
    tokenData = json.load(tokenStorage)
  File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by tobintax** [comment]
@epenet With your recently changes, the "credentials_token.json" file is not empty. Seems ok. 

But I got another error: 

Traceback (most recent call last):
  File "zoe-console.py", line 46, in <module>
    myRenault = MYRenault(credentials['MyRenaultEmail'], credentials['MyRenaultPassword'])
  File "/mnt/scripts/Renault-Zoe-API-master/python/shared/myrenault.py", line 20, in __init__
    if not self.login(email, password):
  File "/mnt/scripts/Renault-Zoe-API-master/python/shared/myrenault.py", line 36, in login
    response = requests.post(url, headers=MYRenault.stealthyHeaders, cookies=self.sessionCookies, data=payload).json()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 894, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
